export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as SignUp } from './SignUp'
export { default as Browse } from './Browse'
export { default as Watch } from './Watch'
export { default as NoMatch } from './NoMatch'
