export { default as Jumbotron } from './Jumbotron'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as Feature } from './Feature'
export { default as FormAlone } from './FormAlone'
export { default as FormAuth } from './FormAuth'
export { default as Navbar } from './Navbar'
export { default as Profile } from './Profile'
export { default as LoadingUser } from './LoadingUser'
export { default as Card } from './Card'
export { default as Player } from './PlayerVideo'
export { default as VolumePlayer } from './PlayerVideo/VolumePlayer'

export { default as Dialog } from './Dialog'
export { default as DialogCardHorizontal } from './DialogCardHorizontal'
export { default as DialogCardVertical } from './DialogCardVertical'
export { default as Watch } from './Watch'
export { default as WatchControl } from './Watch/WatchControl'
